// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenVanCuong2022560.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NguyenVanCuong2022560.NVC0560", b =>
                {
                    b.Property<string>("NVCID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NVCGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NVCName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NVCID");

                    b.ToTable("NVC0560");
                });

            modelBuilder.Entity("NguyenVanCuong2022560.PersonNVC2022560", b =>
                {
                    b.Property<string>("PersonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("PersonNVC2022560");
                });
#pragma warning restore 612, 618
        }
    }
}
